<?xml version="1.0" encoding="UTF-8"?>
<!--*************************************-->
<!--   File    : UsbHostLora.fsproj      -->
<!--   Format  : TopoR Project file      -->
<!--   Version : 2                       -->
<!--   Program : TopoR 8 Layer 7.0.18746 -->
<!--   Date    : Saturday, July 25, 2026 -->
<!--   Time    : 15:39                   -->
<!--*************************************-->

<Project>
   <Version current="2"/>
   <GUID>{53F53737-3E59-455B-92FD-BC04CBDB4714}</GUID>
   <Documents>
      <Section name="PCB" isExpanded="true">
         <File path=".\UsbHostLora.fsx" isopened="1" dateChange="2026-07-25 14:39:29"/>
      </Section>
      <Section name="AutoRouting" isExpanded="false"/>
   </Documents>
</Project>
